-- DROP TABLE IF EXISTS ITEMS, SCENARIOS, CHARACTERS, PARTIES, USERS;

CREATE TABLE USERS (
    USER_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    USER_NAME VARCHAR(50) NOT NULL,
    USER_EMAIL VARCHAR(75) NOT NULL UNIQUE, 
    USER_PASSWORD VARCHAR(100) NOT NULL
) Engine=InnoDB;

CREATE TABLE PARTIES (
    PARTY_ID INT AUTO_INCREMENT PRIMARY KEY,
    PARTYNAME VARCHAR(255) NOT NULL,
    USER_ID INT NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID)
) Engine=InnoDB;

CREATE TABLE CHARACTERS (
    CHAR_ID INT AUTO_INCREMENT PRIMARY KEY,
    CHARNAME VARCHAR(255) NOT NULL,
    TOTALXP INT NOT NULL,
    CHARLEVEL INT NOT NULL,
    GOLD INT NOT NULL,
    PARTY_ID INT NOT NULL,
    FOREIGN KEY (PARTY_ID) REFERENCES PARTIES (PARTY_ID)
) Engine=InnoDB;

CREATE TABLE ITEMS (
    ITEM_ID INT AUTO_INCREMENT PRIMARY KEY,
    ITEMNAME VARCHAR(255) NOT NULL UNIQUE, 
    ITEMTYPE VARCHAR(255)
) Engine=InnoDB;

CREATE TABLE SCENARIOS (
    SCEN_ID INT AUTO_INCREMENT PRIMARY KEY,
    SCENNAME VARCHAR(255) NOT NULL
) Engine=InnoDB;

CREATE TABLE PARTIES_SCENARIOS (
    PARTY_ID INT,
    SCEN_ID INT,
    PRIMARY KEY (PARTY_ID, SCEN_ID),
    FOREIGN KEY (PARTY_ID) REFERENCES PARTIES(PARTY_ID),
    FOREIGN KEY (SCEN_ID) REFERENCES SCENARIOS(SCEN_ID)
) Engine=InnoDB;

CREATE TABLE CHARACTERS_ITEMS (
    CHAR_ID INT,
    ITEM_ID INT,
    PRIMARY KEY (CHAR_ID, ITEM_ID),
    FOREIGN KEY (CHAR_ID) REFERENCES CHARACTERS(CHAR_ID),
    FOREIGN KEY (ITEM_ID) REFERENCES ITEMS(ITEM_ID)
) Engine=InnoDB;
