-- Inserting scenarios
INSERT INTO SCENARIOS (SCENNAME) VALUES ('Roadside Ambush');
INSERT INTO SCENARIOS (SCENNAME) VALUES ('A Hole in the Wall');
INSERT INTO SCENARIOS (SCENNAME) VALUES ('The Black Ship');
INSERT INTO SCENARIOS (SCENNAME) VALUES ('A Ritual in Stone');
INSERT INTO SCENARIOS (SCENNAME) VALUES ('A Deeper Understanding');
INSERT INTO SCENARIOS (SCENNAME) VALUES ('Corrupted Research');
INSERT INTO SCENARIOS (SCENNAME) VALUES ('Sunken Tumor');
INSERT INTO SCENARIOS (SCENNAME) VALUES ('Hidden Tumor');
INSERT INTO SCENARIOS (SCENNAME) VALUES ('Explosive Evolution');
INSERT INTO SCENARIOS (SCENNAME) VALUES ('The Guantlet');
INSERT INTO SCENARIOS (SCENNAME) VALUES ('Defiled Sewers');
INSERT INTO SCENARIOS (SCENNAME) VALUES ('Beguiling Sewers');
INSERT INTO SCENARIOS (SCENNAME) VALUES ('Vile Harvest');
INSERT INTO SCENARIOS (SCENNAME) VALUES ('Toxic Harvest');
INSERT INTO SCENARIOS (SCENNAME) VALUES ('Tainted Blood');
INSERT INTO SCENARIOS (SCENNAME) VALUES ('Mixed Results');
INSERT INTO SCENARIOS (SCENNAME) VALUES ('Red Twilight');
INSERT INTO SCENARIOS (SCENNAME) VALUES ('The Heist');
INSERT INTO SCENARIOS (SCENNAME) VALUES ('Den of Thieves');
INSERT INTO SCENARIOS (SCENNAME) VALUES ('Misplaced Goods');
INSERT INTO SCENARIOS (SCENNAME) VALUES ('Agents of Chaos');
INSERT INTO SCENARIOS (SCENNAME) VALUES ('Unfriendly Message');
INSERT INTO SCENARIOS (SCENNAME) VALUES ('Best of the Best');
INSERT INTO SCENARIOS (SCENNAME) VALUES ('Warding the Void');
INSERT INTO SCENARIOS (SCENNAME) VALUES ('The Greatest Job in the World');

-- Inserting items
INSERT INTO ITEMS (ITEMNAME, ITEMTYPE) VALUES ('Eagle-Eye Goggles', 'head');
INSERT INTO ITEMS (ITEMNAME, ITEMTYPE) VALUES ('Iron Helmet', 'head');
INSERT INTO ITEMS (ITEMNAME, ITEMTYPE) VALUES ('Chain Armor', 'chest');
INSERT INTO ITEMS (ITEMNAME, ITEMTYPE) VALUES ('Studded Leather', 'chest');
INSERT INTO ITEMS (ITEMNAME, ITEMTYPE) VALUES ('Heater Shield', '1 hand');
INSERT INTO ITEMS (ITEMNAME, ITEMTYPE) VALUES ('Throwing Hammer', '1 hand');
INSERT INTO ITEMS (ITEMNAME, ITEMTYPE) VALUES ('Poison Dagger', '1 hand');
INSERT INTO ITEMS (ITEMNAME, ITEMTYPE) VALUES ('Iron Spear', '1 hand');
INSERT INTO ITEMS (ITEMNAME, ITEMTYPE) VALUES ('Weathered Boots', 'legs');
INSERT INTO ITEMS (ITEMNAME, ITEMTYPE) VALUES ('Winged Shoes', 'legs');